import type { ThemePreset } from "../types";

// The "default" preset is special: selecting it calls clearThemePreset()
// to remove all inline overrides and fall back to index.css values.
// The token values here mirror the :root / @variant dark definitions in index.css.
export const defaultPreset: ThemePreset = {
  id: "default",
  name: "Default",
  light: {
    background: "var(--color-white)",
    foreground: "var(--color-neutral-800)",
    card: "var(--color-white)",
    "card-foreground": "var(--color-neutral-800)",
    popover: "var(--color-white)",
    "popover-foreground": "var(--color-neutral-800)",
    primary: "oklch(0.488 0.217 264)",
    "primary-foreground": "var(--color-white)",
    secondary: "--alpha(var(--color-black) / 4%)",
    "secondary-foreground": "var(--color-neutral-800)",
    muted: "--alpha(var(--color-black) / 4%)",
    "muted-foreground": "color-mix(in srgb, var(--color-neutral-500) 90%, var(--color-black))",
    accent: "--alpha(var(--color-black) / 4%)",
    "accent-foreground": "var(--color-neutral-800)",
    destructive: "var(--color-red-500)",
    "destructive-foreground": "var(--color-red-700)",
    border: "--alpha(var(--color-black) / 8%)",
    input: "--alpha(var(--color-black) / 10%)",
    ring: "oklch(0.488 0.217 264)",
    info: "var(--color-blue-500)",
    "info-foreground": "var(--color-blue-700)",
    success: "var(--color-emerald-500)",
    "success-foreground": "var(--color-emerald-700)",
    warning: "var(--color-amber-500)",
    "warning-foreground": "var(--color-amber-700)",
    sidebar: "var(--color-white)",
    "sidebar-foreground": "var(--color-neutral-800)",
    "sidebar-border": "--alpha(var(--color-black) / 8%)",
    "sidebar-accent": "--alpha(var(--color-black) / 4%)",
    "sidebar-accent-foreground": "var(--color-neutral-800)",
  },
  dark: {
    background: "color-mix(in srgb, var(--color-neutral-950) 95%, var(--color-white))",
    foreground: "var(--color-neutral-100)",
    card: "color-mix(in srgb, color-mix(in srgb, var(--color-neutral-950) 95%, var(--color-white)) 98%, var(--color-white))",
    "card-foreground": "var(--color-neutral-100)",
    popover:
      "color-mix(in srgb, color-mix(in srgb, var(--color-neutral-950) 95%, var(--color-white)) 98%, var(--color-white))",
    "popover-foreground": "var(--color-neutral-100)",
    primary: "oklch(0.588 0.217 264)",
    "primary-foreground": "var(--color-white)",
    secondary: "--alpha(var(--color-white) / 4%)",
    "secondary-foreground": "var(--color-neutral-100)",
    muted: "--alpha(var(--color-white) / 4%)",
    "muted-foreground": "color-mix(in srgb, var(--color-neutral-500) 90%, var(--color-white))",
    accent: "--alpha(var(--color-white) / 4%)",
    "accent-foreground": "var(--color-neutral-100)",
    destructive: "color-mix(in srgb, var(--color-red-500) 90%, var(--color-white))",
    "destructive-foreground": "var(--color-red-400)",
    border: "--alpha(var(--color-white) / 6%)",
    input: "--alpha(var(--color-white) / 8%)",
    ring: "oklch(0.588 0.217 264)",
    info: "var(--color-blue-500)",
    "info-foreground": "var(--color-blue-400)",
    success: "var(--color-emerald-500)",
    "success-foreground": "var(--color-emerald-400)",
    warning: "var(--color-amber-500)",
    "warning-foreground": "var(--color-amber-400)",
    sidebar:
      "color-mix(in srgb, color-mix(in srgb, var(--color-neutral-950) 95%, var(--color-white)) 98%, var(--color-white))",
    "sidebar-foreground": "var(--color-neutral-100)",
    "sidebar-border": "--alpha(var(--color-white) / 6%)",
    "sidebar-accent": "--alpha(var(--color-white) / 4%)",
    "sidebar-accent-foreground": "var(--color-neutral-100)",
  },
};
